name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: AWSにログイン
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: "arn:aws:iam::415355479792:role/fukuhara-github-actions-test"

      - name: ECRにログイン
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker イメージをビルド
        run: docker compose build

      - name: イメージにタグ付け
        run: docker tag svelte-todo-app_sveltekit-app ${{ secrets.ECR_REPOSITORY }}:latest

      - name: イメージをECRにpush
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest
